steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/stoked-coder-404402/GCP-practice:$COMMIT_SHA',
      '.'
    

options:
  logging: CLOUD_LOGGING_ONLY