name: React App Deployment # name of the workflow/CI-CD pipeline (will be displayed on github)

on: # conditions that triggers the "workflow" (all stuff inside this yaml file)
  push:
    branches:
      - main # branch name

jobs:
  deploy-react-to-gh-pages: # name of the job (will be displayed on github)
    runs-on: ubuntu-latest # defines what machine type/runner/runner image/virtual machine/virtual environment this job will be run on

                           # The destination machine can be either a GitHub-hosted runner, larger runner, or a self-hosted runner

                           # GitHub-hosted runner :
                                # ubuntu-latest
                                # windows-latest
                                # macos-latest

                           # "larger runner" is a group of github hosted runners

    # env:
    #   EXAMPLE: example # environment variable

    steps:
      # checkout the repository content to github runner
      - name: Checkout  # name of a step (will be displayed on github)
        uses: actions/checkout@v2 # selects an "action" to run as part of a step in a job, "actions/checkout@v2" is the "action" in this case
                                  # an action is a reusable unit of code (just an yaml file).
                                  # you can use an action defined in the same repository as the workflow, a public repository, or in a published Docker container image.
                                  # what actions/checkout@v2 does is checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
                                  # info about actions/checkout@v2 : https://github.com/actions/checkout

      # setup nodejs environment
      - name: Setup Node.js environment  # (will be displayed on github)
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18.17.1"

      # cache the dependencies to speed up the build
      - name: Cache dependencies   # (will be displayed on github)
                                   # "This action allows caching dependencies and build outputs to improve workflow execution time." from https://github.com/actions/cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # install dependencies
      - name: Install dependencies   # (will be displayed on github)
        run: npm i

      # build the react app
      - name: Build   # (will be displayed on github)
        run: npm run build

      # deploy the react app to github pages
      - name: Deploy  # (will be displayed on github)
        uses: peaceiris/actions-gh-pages@v3 # this is a predefined action from here : https://github.com/peaceiris/actions-gh-pages
                                            # what is does is deploy your static files to GitHub Pages/push any static content to github pages
        with:
          # NOTE: GITHUB_TOKEN is a secret token that is automatically generated by GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # directory to deploy